theme: jekyll-theme-minimal
title: Jake Brawer, Ph.D
description: "Computer science Ph.D from Yale.<br>Postdoc at CU Boulder.<br>Social Roboticist."
email: <a href="https://mailhide.io/en/e/cb2eTmo6"> Email</a>
url: "http://jakebrawer.github.io/"
headshot: /img/jake_bw_circle.jpg


permalink: pretty
