theme: jekyll-theme-minimal
title: Jake Brawer, Ph.D
description: Computer science Ph.D from Yale University. Social Robotics
email: jake.brawer@yale.edu
url: "http://jakebrawer.github.io/"

permalink: pretty
