theme: jekyll-theme-minimal
title: Jake Brawer
description: Computer science Ph.D. candidate.Yale University.Social Robotics
email: jake.brawer@yale.edu
url: "http://jakebrawer.github.io/"

permalink: pretty
