theme: jekyll-theme-minimal
title: Jake Brawer, Ph.D
description: "Computer science Ph.D from Yale.<br>Postdoc at CU Boulder.<br>Social Roboticist."
email: jake.brawer@colorado.edu
url: "http://jakebrawer.github.io/"

permalink: pretty
