theme: jekyll-theme-minimal
title: Jake Brawer, Ph.D.
description: "AI and robotics researcher/engineer.<br>Computer science Ph.D. from Yale.<br>Human-centered AI systems."
email: <a href="mailto:careers.swagger755@passmail.net">Email</a>
url: "https://jakebrawer.github.io"
headshot: /img/jake_bw_circle.jpg


permalink: pretty
